#!/usr/bin/env python

# you're going to need BeautifulSoup and python 3
import sys
import os
from urllib.request import urlopen
from bs4 import BeautifulSoup
import subprocess

url = sys.argv[1]
html = urlopen(url).read().decode("utf8")

soup = BeautifulSoup(html, "html.parser")
header = soup.find("h1").get_text().splitlines()[0]

dir_and_exe = "-".join(header.lower().split())

subprocess.call(["cabal", "build", dir_and_exe])
